/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author hasser
 */
public class InventoryPane extends javax.swing.JPanel {

    /**
     * Creates new form Compras
     */
    public InventoryPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameStcLabel = new javax.swing.JLabel();
        numStcLabel = new javax.swing.JLabel();
        provStcBox = new javax.swing.JComboBox<>();
        provStcLabel = new javax.swing.JLabel();
        buyStcBtn = new javax.swing.JButton();
        cleanStcBtn = new javax.swing.JButton();
        nameStcText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stcTable = new javax.swing.JTable();
        delStcBtn = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setLayout(null);

        nameStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameStcLabel.setText("Articulo:");
        add(nameStcLabel);
        nameStcLabel.setBounds(40, 100, 75, 26);

        numStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        numStcLabel.setText("Cantidad:");
        add(numStcLabel);
        numStcLabel.setBounds(30, 160, 85, 26);

        provStcBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provStcBoxActionPerformed(evt);
            }
        });
        add(provStcBox);
        provStcBox.setBounds(130, 211, 150, 40);

        provStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        provStcLabel.setText("Proveedor:");
        add(provStcLabel);
        provStcLabel.setBounds(20, 220, 97, 26);

        buyStcBtn.setText("Comprar");
        buyStcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyStcBtnActionPerformed(evt);
            }
        });
        add(buyStcBtn);
        buyStcBtn.setBounds(20, 290, 90, 50);

        cleanStcBtn.setText("Limpiar");
        cleanStcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanStcBtnActionPerformed(evt);
            }
        });
        add(cleanStcBtn);
        cleanStcBtn.setBounds(120, 290, 90, 50);
        add(nameStcText);
        nameStcText.setBounds(130, 90, 150, 40);

        stcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ARTICULO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(stcTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(332, 34, 360, 330);

        delStcBtn.setText("Borrar");
        delStcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStcBtnActionPerformed(evt);
            }
        });
        add(delStcBtn);
        delStcBtn.setBounds(220, 290, 100, 50);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 200, 1));
        add(jSpinner1);
        jSpinner1.setBounds(130, 150, 60, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void provStcBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provStcBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provStcBoxActionPerformed

    private void delStcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStcBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delStcBtnActionPerformed

    private void cleanStcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanStcBtnActionPerformed

    }//GEN-LAST:event_cleanStcBtnActionPerformed

    private void buyStcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyStcBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyStcBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyStcBtn;
    private javax.swing.JButton cleanStcBtn;
    private javax.swing.JButton delStcBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel nameStcLabel;
    private javax.swing.JTextField nameStcText;
    private javax.swing.JLabel numStcLabel;
    private javax.swing.JComboBox<String> provStcBox;
    private javax.swing.JLabel provStcLabel;
    private javax.swing.JTable stcTable;
    // End of variables declaration//GEN-END:variables
}
