/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
    
public class ProviderPane extends javax.swing.JPanel {
    
    private void init() throws SQLException{
        initComponents();
        chargeTable();
    }
    DBC con = DBC.getInstance();
    public ProviderPane(){
        try{
            init();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameProvLabel = new javax.swing.JLabel();
        telProvLabel = new javax.swing.JLabel();
        nameProvText = new javax.swing.JTextField();
        telProvText = new javax.swing.JTextField();
        addProvBtn = new javax.swing.JButton();
        cleanProvBtn = new javax.swing.JButton();
        delProvBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        provTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(null);

        nameProvLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameProvLabel.setText("Nombre:");
        add(nameProvLabel);
        nameProvLabel.setBounds(60, 120, 79, 26);

        telProvLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        telProvLabel.setText("Telefono:");
        add(telProvLabel);
        telProvLabel.setBounds(60, 190, 83, 26);

        nameProvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProvTextActionPerformed(evt);
            }
        });
        add(nameProvText);
        nameProvText.setBounds(150, 110, 189, 35);
        add(telProvText);
        telProvText.setBounds(150, 180, 189, 40);

        addProvBtn.setText("Agregar");
        addProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProvBtnActionPerformed(evt);
            }
        });
        add(addProvBtn);
        addProvBtn.setBounds(32, 240, 106, 50);

        cleanProvBtn.setText("Limpiar");
        cleanProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanProvBtnActionPerformed(evt);
            }
        });
        add(cleanProvBtn);
        cleanProvBtn.setBounds(150, 240, 100, 50);

        delProvBtn.setText("Borrar");
        delProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delProvBtnActionPerformed(evt);
            }
        });
        add(delProvBtn);
        delProvBtn.setBounds(262, 240, 101, 50);

        provTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(provTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(369, 57, 290, 272);
    }// </editor-fold>//GEN-END:initComponents

    private void nameProvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProvTextActionPerformed
    private void chargeTable() throws SQLException{
        try{
            DefaultTableModel model = new DefaultTableModel();
            provTable.setModel(model);
            Connection connection = con.open();
            PreparedStatement provSel = connection.prepareStatement("Select id,name,tel from providers");

            ResultSet data = provSel.executeQuery();
            
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Telefono");
            provTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            provTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            provTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            
            while(data.next()){
                Object row[] = new Object[3];
                for(int i=0;i<3;i++){
                    row[i] = data.getObject(i+1);
                }
                model.addRow(row);
            }
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    private void addProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProvBtnActionPerformed
        if(nameProvText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Nombre vacio");
            return;
        }
        if(telProvText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Telefono vacio");
            return;
        }
        
        try{
            Connection connection = con.open();
            
            PreparedStatement addProv = connection.prepareStatement("insert into providers values (?,?,?)");
            addProv.setString(1, "0");
            addProv.setString(2,nameProvText.getText().trim().toUpperCase());
            addProv.setString(3,telProvText.getText().trim().toUpperCase());
            addProv.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proveedor añadido");
            chargeTable();
            cleanProvBtnActionPerformed(evt);
            con.close();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }//GEN-LAST:event_addProvBtnActionPerformed

    private void cleanProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanProvBtnActionPerformed
        nameProvText.setText("");
        telProvText.setText("");
    }//GEN-LAST:event_cleanProvBtnActionPerformed

    private void delProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delProvBtnActionPerformed
        if(provTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Selecciona una fila");
            return;
        }
        try{
            Connection connection = con.open();
            PreparedStatement delProv = connection.prepareStatement("delete from providers where id = ?");
            delProv.setString(1, provTable.getModel().getValueAt(provTable.getSelectedRow(), 0).toString());
            delProv.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
            chargeTable();
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: " + e);

        }
    }//GEN-LAST:event_delProvBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProvBtn;
    private javax.swing.JButton cleanProvBtn;
    private javax.swing.JButton delProvBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameProvLabel;
    private javax.swing.JTextField nameProvText;
    private javax.swing.JTable provTable;
    private javax.swing.JLabel telProvLabel;
    private javax.swing.JTextField telProvText;
    // End of variables declaration//GEN-END:variables
}
