/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author hasser
 */
public class SellPane extends javax.swing.JPanel {

    /**
     * Creates new form VentasPanel
     */
    public SellPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nameSellLabel = new javax.swing.JLabel();
        numSellLabel = new javax.swing.JLabel();
        totalSellLabel = new javax.swing.JLabel();
        numSellSpinner = new javax.swing.JSpinner();
        nameSellText = new java.awt.TextField();
        totalSellText = new java.awt.TextField();
        addSellBtn = new javax.swing.JButton();
        cleanSellBtn = new javax.swing.JButton();
        sellSellBtn = new javax.swing.JButton();
        delSellBtn = new javax.swing.JButton();
        cancelSellBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sellTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        nameSellLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameSellLabel.setText("Producto:");

        numSellLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        numSellLabel.setText("Cantidad:");

        totalSellLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        totalSellLabel.setText("Total:");

        numSellSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numSellSpinner.setValue(1);

        nameSellText.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        nameSellText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSellTextActionPerformed(evt);
            }
        });

        totalSellText.setEditable(false);
        totalSellText.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        totalSellText.setText("$0");
        totalSellText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSellTextActionPerformed(evt);
            }
        });

        addSellBtn.setText("Agregar");
        addSellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSellBtnActionPerformed(evt);
            }
        });

        cleanSellBtn.setText("Limpiar");
        cleanSellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanSellBtnActionPerformed(evt);
            }
        });

        sellSellBtn.setText("Compra");
        sellSellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellSellBtnActionPerformed(evt);
            }
        });

        delSellBtn.setText("Borrar");

        cancelSellBtn.setText("Cancelar");
        cancelSellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSellBtnActionPerformed(evt);
            }
        });

        sellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane3.setViewportView(sellTable);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("Total:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jTextField1.setText("$0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalSellLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numSellLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalSellText, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numSellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameSellLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameSellText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(addSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cleanSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(delSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameSellLabel)
                            .addComponent(nameSellText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numSellLabel)
                            .addComponent(numSellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalSellLabel)
                            .addComponent(totalSellText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSellBtn)
                            .addComponent(cleanSellBtn)
                            .addComponent(sellSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cancelSellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameSellTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSellTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSellTextActionPerformed

    private void totalSellTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSellTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSellTextActionPerformed

    private void addSellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSellBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSellBtnActionPerformed

    private void sellSellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellSellBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellSellBtnActionPerformed

    private void cleanSellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanSellBtnActionPerformed

        nameSellText.setText("");
        numSellSpinner.setValue(1);
        totalSellText.setText("$0");
    }//GEN-LAST:event_cleanSellBtnActionPerformed

    private void cancelSellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSellBtnActionPerformed
        if(evt.getSource() == cancelSellBtn){
            cleanSellBtnActionPerformed(evt);
            sellTable.removeAll();
        }
    }//GEN-LAST:event_cancelSellBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSellBtn;
    private javax.swing.JButton cancelSellBtn;
    private javax.swing.JButton cleanSellBtn;
    private javax.swing.JButton delSellBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nameSellLabel;
    private java.awt.TextField nameSellText;
    private javax.swing.JLabel numSellLabel;
    private javax.swing.JSpinner numSellSpinner;
    private javax.swing.JButton sellSellBtn;
    private javax.swing.JTable sellTable;
    private javax.swing.JLabel totalSellLabel;
    private java.awt.TextField totalSellText;
    // End of variables declaration//GEN-END:variables
}
