/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author hasser
 */
public class SrchProductPane extends javax.swing.JPanel {

    /**
     * Creates new form ProductoPanel
     */
    public SrchProductPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameSrchProdText = new javax.swing.JTextField();
        nameSrchProdLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        srchProdTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(null);

        nameSrchProdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSrchProdTextActionPerformed(evt);
            }
        });
        add(nameSrchProdText);
        nameSrchProdText.setBounds(255, 21, 224, 27);

        nameSrchProdLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameSrchProdLabel.setText("Producto: ");
        add(nameSrchProdLabel);
        nameSrchProdLabel.setBounds(137, 19, 91, 26);

        srchProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CATEGORIA"
            }
        ));
        jScrollPane2.setViewportView(srchProdTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(29, 66, 641, 276);
    }// </editor-fold>//GEN-END:initComponents

    private void nameSrchProdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSrchProdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSrchProdTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameSrchProdLabel;
    private javax.swing.JTextField nameSrchProdText;
    private javax.swing.JTable srchProdTable;
    // End of variables declaration//GEN-END:variables
}
