/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hasser
 */
public class SrchProductPane extends javax.swing.JPanel {
    
    DBC con = DBC.getInstance();
    public SrchProductPane() {
        initComponents();
        chargeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameSrchProdText = new javax.swing.JTextField();
        nameSrchProdLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        srchProdTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        nameSrchProdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSrchProdTextActionPerformed(evt);
            }
        });
        nameSrchProdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameSrchProdTextKeyReleased(evt);
            }
        });

        nameSrchProdLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameSrchProdLabel.setText("Producto: ");

        srchProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "CATEGORIA"
            }
        ));
        jScrollPane2.setViewportView(srchProdTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(nameSrchProdLabel)
                        .addGap(27, 27, 27)
                        .addComponent(nameSrchProdText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSrchProdLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nameSrchProdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameSrchProdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSrchProdTextActionPerformed
                        
    }//GEN-LAST:event_nameSrchProdTextActionPerformed
    public void chargeTable(){
        try{
            DefaultTableModel model = new DefaultTableModel();
            srchProdTable.setModel(model);
            Connection connection = con.open();
            PreparedStatement selProd = connection.prepareStatement("select p.id,p.name,p.price,p.quantity,c.name "
                    + "from products as p, categorys as c"
                    + " where p.id_category = c.id AND "
                    + "p.name LIKE \"%"+ nameSrchProdText.getText().trim().toUpperCase() +"%\"");
            
            ResultSet data = selProd.executeQuery();
            model.addColumn("ID");
            model.addColumn("NOMBRE");
            model.addColumn("PRECIO");
            model.addColumn("CANTIDAD");
            model.addColumn("CATEGORIA");
            srchProdTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            srchProdTable.getColumnModel().getColumn(1).setPreferredWidth(75);
            srchProdTable.getColumnModel().getColumn(2).setPreferredWidth(75);
            srchProdTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            srchProdTable.getColumnModel().getColumn(4).setPreferredWidth(75);
            while(data.next()){
                Object row[] = new Object[5];
                for(int i=0;i<5;i++){
                    row[i] = data.getObject(i+1);
                }
                model.addRow(row);
            }
            con.close();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }
    private void nameSrchProdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSrchProdTextKeyReleased
        chargeTable();
    }//GEN-LAST:event_nameSrchProdTextKeyReleased
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameSrchProdLabel;
    private javax.swing.JTextField nameSrchProdText;
    private javax.swing.JTable srchProdTable;
    // End of variables declaration//GEN-END:variables
}
