package admin;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class UserPane extends javax.swing.JPanel {

    DBC con =  DBC.getInstance();
    
    public UserPane() throws SQLException{
        initComponents();
        chargeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser1 = new javax.swing.JTable();
        idUserLabel = new javax.swing.JLabel();
        nameUserLabel = new javax.swing.JLabel();
        permUserBox = new javax.swing.JComboBox<>();
        addUserBtn = new javax.swing.JButton();
        cleanUserBtn = new javax.swing.JButton();
        delUserBtn = new javax.swing.JButton();
        idUserText = new javax.swing.JTextField();
        nameUserText = new javax.swing.JTextField();
        pwdUserLabel = new javax.swing.JLabel();
        permUserLabel = new javax.swing.JLabel();
        pwdUserText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        tableUser1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PERMISO"
            }
        ));
        jScrollPane2.setViewportView(tableUser1);

        idUserLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        idUserLabel.setText("ID:");

        nameUserLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameUserLabel.setText("Nombre:");

        permUserBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajador", "Administrador", "Jefe (no crear)" }));
        permUserBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permUserBoxActionPerformed(evt);
            }
        });

        addUserBtn.setText("Agregar");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        cleanUserBtn.setText("Limpiar");
        cleanUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanUserBtnActionPerformed(evt);
            }
        });

        delUserBtn.setText("Borrar");
        delUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserBtnActionPerformed(evt);
            }
        });

        pwdUserLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        pwdUserLabel.setText("Contraseña:");

        permUserLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        permUserLabel.setText("Permiso:");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PERMISO"
            }
        ));
        userTable.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(userTable);
        userTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idUserLabel)
                            .addComponent(pwdUserLabel)
                            .addComponent(nameUserLabel)
                            .addComponent(permUserLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameUserText)
                            .addComponent(pwdUserText)
                            .addComponent(permUserBox, 0, 142, Short.MAX_VALUE)
                            .addComponent(idUserText))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idUserLabel)
                            .addComponent(idUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameUserLabel)
                            .addComponent(nameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdUserLabel))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(permUserBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permUserLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleanUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void permUserBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permUserBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permUserBoxActionPerformed

    private void cleanUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanUserBtnActionPerformed
        idUserText.setText("");
        nameUserText.setText("");
        pwdUserText.setText("");
        permUserBox.setSelectedIndex(0);

    }//GEN-LAST:event_cleanUserBtnActionPerformed
    private void chargeTable() throws SQLException{
        try{
            DefaultTableModel model = new DefaultTableModel();
            userTable.setModel(model);
            Connection connection = con.open();
            PreparedStatement userSel = connection.prepareStatement("Select id,name,permission from user");

            ResultSet data = userSel.executeQuery();
            ResultSetMetaData metadata = userSel.getMetaData();
            int numCol = metadata.getColumnCount();
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Permiso");
            userTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            userTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            userTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            while(data.next()){
                Object row[] = new Object[3];
                for(int i=0;i<3;i++){
                    row[i] = data.getObject(i+1);
                }
                model.addRow(row);
            }
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        try{
            Connection connection = con.open();
            PreparedStatement addUser = connection.prepareStatement("insert into user values(?,?,?,?)");
            addUser.setString(1, idUserText.getText().trim().toUpperCase());
            addUser.setString(2, nameUserText.getText().trim().toUpperCase());
            addUser.setString(3, pwdUserText.getText().trim());
            addUser.setString(4, permUserBox.getSelectedItem().toString().toUpperCase());
            addUser.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario añadido");
            chargeTable();
            cleanUserBtnActionPerformed(evt);
            con.close();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void delUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserBtnActionPerformed
        if(userTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Selecciona una fila");
            return;
        }
        try{
            Connection connection = con.open();
            PreparedStatement delUser = connection.prepareStatement("delete from user where id = ?");
            delUser.setString(1, userTable.getModel().getValueAt(userTable.getSelectedRow(), 0).toString());
            
            delUser.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
            chargeTable();
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error: " + e);

        }
    }//GEN-LAST:event_delUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton cleanUserBtn;
    private javax.swing.JButton delUserBtn;
    private javax.swing.JLabel idUserLabel;
    private javax.swing.JTextField idUserText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameUserLabel;
    private javax.swing.JTextField nameUserText;
    private javax.swing.JComboBox<String> permUserBox;
    private javax.swing.JLabel permUserLabel;
    private javax.swing.JLabel pwdUserLabel;
    private javax.swing.JTextField pwdUserText;
    private javax.swing.JTable tableUser1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
