/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author hasser
 */
public class WorkerView extends javax.swing.JFrame {

    /**
     * Creates new form WorkerView
     */
    public WorkerView(String user) {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Administrador de Negocios");
        usernameViewText.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryPane1 = new admin.CategoryPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        srchProductPane1 = new admin.SrchProductPane();
        sellPane1 = new admin.SellPane();
        usernameViewLabel = new javax.swing.JLabel();
        usernameViewText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Buscar Producto", srchProductPane1);
        jTabbedPane1.addTab("Vender", sellPane1);

        usernameViewLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        usernameViewLabel.setText("Usuario:");

        usernameViewText.setEditable(false);
        usernameViewText.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        usernameViewText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameViewText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameViewLabel)
                    .addComponent(usernameViewText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admin.CategoryPane categoryPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private admin.SellPane sellPane1;
    private admin.SrchProductPane srchProductPane1;
    private javax.swing.JLabel usernameViewLabel;
    private javax.swing.JTextField usernameViewText;
    // End of variables declaration//GEN-END:variables
}
