/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author hasser
 */
public class InventoryPane extends javax.swing.JPanel {

    /**
     * Creates new form Compras
     */
    public InventoryPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameStcLabel = new javax.swing.JLabel();
        numStcLabel = new javax.swing.JLabel();
        provStcBox = new javax.swing.JComboBox<>();
        provStcLabel = new javax.swing.JLabel();
        buyStcBtn = new javax.swing.JButton();
        cleanStcBtn = new javax.swing.JButton();
        nameStcText = new javax.swing.JTextField();
        numStcText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stcTable = new javax.swing.JTable();
        delStcBtn = new javax.swing.JButton();

        nameStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameStcLabel.setText("Articulo:");

        numStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        numStcLabel.setText("Cantidad:");

        provStcBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provStcBoxActionPerformed(evt);
            }
        });

        provStcLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        provStcLabel.setText("Proveedor:");

        buyStcBtn.setText("Comprar");

        cleanStcBtn.setText("Limpiar");

        stcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ARTICULO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(stcTable);

        delStcBtn.setText("Borrar");
        delStcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStcBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(buyStcBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cleanStcBtn)
                                .addGap(25, 25, 25)
                                .addComponent(delStcBtn))
                            .addComponent(nameStcLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(numStcLabel)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(provStcLabel)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numStcText)
                            .addComponent(nameStcText)
                            .addComponent(provStcBox, 0, 150, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameStcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameStcLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numStcLabel)
                            .addComponent(numStcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provStcBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provStcLabel))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyStcBtn)
                            .addComponent(cleanStcBtn)
                            .addComponent(delStcBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void provStcBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provStcBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provStcBoxActionPerformed

    private void delStcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStcBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delStcBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyStcBtn;
    private javax.swing.JButton cleanStcBtn;
    private javax.swing.JButton delStcBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameStcLabel;
    private javax.swing.JTextField nameStcText;
    private javax.swing.JLabel numStcLabel;
    private javax.swing.JTextField numStcText;
    private javax.swing.JComboBox<String> provStcBox;
    private javax.swing.JLabel provStcLabel;
    private javax.swing.JTable stcTable;
    // End of variables declaration//GEN-END:variables
}
