/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author hasser
 */
public class ProviderPane extends javax.swing.JPanel {

    /**
     * Creates new form ProveedoresPanel
     */
    public ProviderPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameProvLabel = new javax.swing.JLabel();
        telProvLabel = new javax.swing.JLabel();
        nameProvText = new javax.swing.JTextField();
        telProvText = new javax.swing.JTextField();
        addProvBtn = new javax.swing.JButton();
        cleanProvBtn = new javax.swing.JButton();
        delProvBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        provTable = new javax.swing.JTable();

        nameProvLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nameProvLabel.setText("Nombre:");

        telProvLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        telProvLabel.setText("Telefono:");

        nameProvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProvTextActionPerformed(evt);
            }
        });

        addProvBtn.setText("Agregar");
        addProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProvBtnActionPerformed(evt);
            }
        });

        cleanProvBtn.setText("Limpiar");

        delProvBtn.setText("Borrar");

        provTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(provTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameProvLabel)
                            .addComponent(telProvLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telProvText, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(nameProvText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cleanProvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delProvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameProvLabel)
                            .addComponent(nameProvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telProvLabel)
                            .addComponent(telProvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProvBtn)
                            .addComponent(cleanProvBtn)
                            .addComponent(delProvBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameProvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProvTextActionPerformed

    private void addProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProvBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProvBtn;
    private javax.swing.JButton cleanProvBtn;
    private javax.swing.JButton delProvBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameProvLabel;
    private javax.swing.JTextField nameProvText;
    private javax.swing.JTable provTable;
    private javax.swing.JLabel telProvLabel;
    private javax.swing.JTextField telProvText;
    // End of variables declaration//GEN-END:variables
}
